### PR TITLE
Issue / Bug Roll Up

### PR DESCRIPTION
**Pull request by ColinRobbins**
A roll up of PRs to make merging easy for @HandyHat .

For a full description - see https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/137.

## Description
This PR contains a roll up of the following PRs, that could be closed if the PR accepted.
* https://github.com/HandyHat/ha-hildebrandglow-dcc/pull/77 - alternative solution implemented  - as discussed in thread
* https://github.com/HandyHat/ha-hildebrandglow-dcc/pull/135 - alternative solution implemented.   Rather than set the time to 30 minutes.   Run it every 5 minutes, but only call glow API if between 00 and 05 or 30 and 35 minutes past the hour - as advised on [Glow forum](https://forum.glowmarkt.com/index.php?p=/discussion/comment/544/#Comment_544).
* https://github.com/HandyHat/ha-hildebrandglow-dcc/pull/136 - alternative solution implemented.   Rather than set the time to 30 minutes.   Run it every 5 minutes, but only call glow API if between 00 and 05 or 30 and 35 minutes past the hour - as advised on [Glow forum](https://forum.glowmarkt.com/index.php?p=/discussion/comment/544/#Comment_544).

Please do not add comments on the PR unelss it is about a coding issue on the PR.
Please add more general comments to the related [issue](https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/137) - this will make tracking easier.

### CODE REVIEW

**Comment by HandyHat** [comment]
This looks great @ColinRobbins - thank you so much!

**Comment by HarvsG** [comment]
Could we have a new release to implement this change? Because installing via HACS gave me the release from November which was still bugged.

**Comment by ColinRobbins** [comment]
Sadly only @HandyHat can do that.
In the meantime, you can copy and overwrite the .py files.

**Comment by HandyHat** [comment]
v0.6.0 has now actually been released. You can also install directly from main on HACS to get pre-release changes.

**Pull request merged**
