### PR TITLE
Improved Error Handling & Correct Units

### PR DESCRIPTION
**Pull request by ColinRobbins**
## Description

Fix of two open issues.

## Motivation and Context

Fix for https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/52
Fix for https://github.com/HandyHat/ha-hildebrandglow-dcc/issues/53

## How Has This Been Tested?

Locally and by @si458 and @townsmcp

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by HandyHat — CHANGES_REQUESTED** [review]
I think setting available to false when an error is encountered is preferred as that will stop the integration continually polling when there is no tariff data available.
The only downside is that once tariff data is added, the integration will need to be restarted, but I don't think that's unreasonable.

**Comment by ColinRobbins** [comment]
Sorry I don't understand your requested change to `available`.
Can you elaborate please?

I think anything that relies on a restart seems wrong to me.
As soon as the tarif data is available, it should be pulled.
What if a temporary error (such as Glow being unavailable) occurs, then I'd have to restart once the API is fixed.

Surpressing logs are one failure is becoming common in other integrations.

Surely this is better than the current behaviour, which is filling up log files as we speak!

**Comment by ColinRobbins** [comment]
NB:  This PR fixes the "incorrect units" bug too.
Do you want a seperate PR for that, while we agree the "logging" approach?

**Comment by si458** [comment]
@ColinRobbins you are correct with using the PR as my issue the other day when the API was down #59
the minute the API returned data, it was in home assistant, where i didnt have to restart my pi
(@HandyHat think HIVE integration, they have an API outage, HA still carrys on, you dont have to restart it JUST to get data again?, so personally this PR is fine)

**Comment by si458** [comment]
> NB: This PR fixes the "incorrect units" bug too. Do you want a seperate PR for that, while we agree the "logging" approach?

best to split them yeh

**Comment by HandyHat** [comment]
> What if a temporary error (such as Glow being unavailable) occurs, then I'd have to restart once the API is fixed.

Didn't consider that - you are absolutely right.

I'd still like to investigate setting some entities to unavailable (which means home assistant doesn't bother polling for data) when tariff data is not available, but we can track that in #55. For now I'll go ahead and merge!

Thanks @ColinRobbins

**Pull request merged**
