### PR TITLE
Improved error handling when Tariff data unavailable & other minor enhancements.

### PR DESCRIPTION
**Pull request by ColinRobbins**
## Description

This PR contains the following enhancements:
- If Tariff data is unavailable (as indicated as a failure to ever retrieve data), rather than retry every 2 minutes (which will repeatedly fail), it backs off to trying once per day.
- If Tariff data is temporarily unavailable (indicated by data having been previously been retrieved), there is no change to behaviour.
- When data is not available the sensor status is set to "unavailable" instead of "unknown".
- Reading  the Tariff rate data waits for 2 seconds to allow the data to arrive from the buddy Standing Rate sensor.  Without this the Tariff rate data is always one update cycle out of date (2 minutes),

## Motivation and Context

Enhancements

## How Has This Been Tested?

Run in local test and live environment.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Bod1985** [comment]
Any news on this? My tariff doesn’t seem to be available in the Bright app and thus also not available in the integration

**Comment by ColinRobbins** [comment]
No, no news @HandyHat has gone silent for a while.
In any case, if the data is not showing in Bright, all this PR will do is better error handling.   The real solution is to get your energy provider to fix the issue.

**Comment by HandyHat** [comment]
Apologies - been having some issues with my Home Assistant instance which means I haven't been able to locally test this. Will have a look soon!

**Comment by ColinRobbins** [comment]
To be replace with a roll up...

**Pull request closed without merging**
